'use client';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Spotlight } from "@/components/ui/Spotlight";
import Navbar from "@/components/Navbar";
import LoginPage from "./login/page";
import SignupPage from "./signup/page";
import { useInitializeCometChat } from "@/utils/cometchatConfig";
import { useEffect } from "react";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useInitializeCometChat();

  return (
    <html lang="en" className="dark overflow-x-hidden">
      <body className={inter.className}>
      <div className='relative w-screen'>
        {window.location.pathname !== '/login' && window.location.pathname !== '/signup' && <Navbar />}
      </div>
      <Spotlight
        className="left-40  md:left-60 md:-top-20"
        fill="blue"
      />
        
        {children}
        </body>
    </html>
  );
}
